# Generated by Django 2.2.3 on 2020-03-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
