# Generated by Django 2.2.3 on 2020-03-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0003_auto_20200315_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='userProfile',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='owner',
        ),
    ]
