# Generated by Django 2.2.3 on 2020-03-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0012_auto_20200315_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
