# Generated by Django 2.2.3 on 2020-03-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0013_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='owner',
        ),
    ]
