# Generated by Django 2.2.3 on 2020-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0014_auto_20200316_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
