# Generated by Django 2.2.3 on 2020-03-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0015_auto_20200316_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userName',
        ),
    ]
