# Generated by Django 2.2.3 on 2020-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0016_auto_20200317_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
