# Generated by Django 2.2.3 on 2020-03-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow', '0017_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='question',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
